### PR TITLE
Changed name generation

### PR DESCRIPTION
**Pull request by AndrejScak**
According to MS documentation name should be in format 'en-US-JessaRUS'

### CODE REVIEW

**Comment by jeroenterheerdt** [comment]
where is the doc for that?

**Comment by AndrejScak** [comment]
On their website
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-text-to-speech

**Comment by jeroenterheerdt** [comment]
have you tested the code with this updated item?

**Comment by AndrejScak** [comment]
Just with Postman...
I tried to use other than English language and I always got response error code 400, than I tried with Postman and I with this modification response from server is OK.

**Comment by jeroenterheerdt** [comment]
ok, thanks.

**Pull request merged**
